
package grupp9_uppgift2;

import javax.swing.table.TableModel;

/**
 *
 * @author Joel
 */
public class MainView extends javax.swing.JFrame {

    Controller controller;

    /**
     * Creates new form MainView
     * 
     * @param controller Handler communication with DataAccessLayer
     */
    public MainView(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneResults = new javax.swing.JScrollPane();
        tblListResults = new javax.swing.JTable();
        btnUpdateTable = new javax.swing.JButton();
        comboListQuerySelector = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronus Database Browser");

        tblListResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPaneResults.setViewportView(tblListResults);

        btnUpdateTable.setText("Updatera");
        btnUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableActionPerformed(evt);
            }
        });

        comboListQuerySelector.setMaximumRowCount(10);
        comboListQuerySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CRONUS Employees and related tables content", "CRONUS Employee and related tables MetaData", "CRONUS Employee Columns 1", "CRONUS Employee Columns 2", "CRONUS Keys", "CRONUS Indexes", "CRONUS Constraints", "CRONUS Tables 1", "CRONUS Tables 2", "CRONUS Table with most rows" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboListQuerySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboListQuerySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableActionPerformed
        int comboIndex = this.comboListQuerySelector.getSelectedIndex();
        TableModel tm;
        //Inget valt
        
        switch (comboIndex) {
            case 0:
                //CRONUS Employees and related tables
                tm = controller.getCronusEmployees();
                this.tblListResults.setModel(tm);
                break;
            case 1:
                //CRONUS Employee MetaData
                tm = controller.getCronusEmployeeMetaData();
                this.tblListResults.setModel(tm);
                break;
            case 2:
                //CRONUS Employee Columns1
                tm = controller.getCronusEmployeeColumns1();
                this.tblListResults.setModel(tm);
                break;
            case 3:
                //CRONUS Employee Columns2
                tm = controller.getCronusEmployeeColumns2();
                this.tblListResults.setModel(tm);
                break;
            case 4:
                //CRONUS Keys
                tm = controller.getCronusKeys();
                this.tblListResults.setModel(tm);
                break;
            case 5:
                //CRONUS Indexes
                tm = controller.getCronusIndexes();
                this.tblListResults.setModel(tm);
                break;
            case 6:
                //CRONUS Constraints
                tm = controller.getCronusConstraints();
                this.tblListResults.setModel(tm);
                break;
            case 7:
                //CRONUS Tables1
                tm = controller.getCronusTables1();
                this.tblListResults.setModel(tm);
                break;
            case 8:
                //CRONUS Tables2
                tm = controller.getCronusTables2();
                this.tblListResults.setModel(tm);
                break;
            case 9:
                //CRONUS Tables
                tm = controller.getCronusTableWithMostRows();
                this.tblListResults.setModel(tm);
                break;
            default:
                System.out.println("Combobox inoput out of switch range");
        }

    }//GEN-LAST:event_btnUpdateTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateTable;
    private javax.swing.JComboBox comboListQuerySelector;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JTable tblListResults;
    // End of variables declaration//GEN-END:variables
}
