/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grupp9_labb1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author svalan
 */
public class GUI extends javax.swing.JFrame {
    
    Controller controller;

    /**
     * Creates new form GUI
     */
    public GUI(Controller controller) {
        
        this.controller = controller;
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsomnia = new javax.swing.JButton();
        btnInsomniaHosta = new javax.swing.JButton();
        btnNoCar = new javax.swing.JButton();
        btnNoOwner = new javax.swing.JButton();
        btnTotalWages = new javax.swing.JButton();
        btnIncreasedWage = new javax.swing.JButton();
        btnFirstLetter = new javax.swing.JButton();
        btnNameDisease = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsomnia.setText("1) Vilka patienter lider av insomnia?");
        btnInsomnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsomniaActionPerformed(evt);
            }
        });

        btnInsomniaHosta.setText("2) Namn på alla patienter som lider av imsomnia eller hosta");
        btnInsomniaHosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsomniaHostaActionPerformed(evt);
            }
        });

        btnNoCar.setText("3) Namn på anställda som inte har någon bil");
        btnNoCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoCarActionPerformed(evt);
            }
        });

        btnNoOwner.setText("4) Regnr på alla bilar som inte har någon ägare");

        btnTotalWages.setText("5) Total lönekostnad");

        btnIncreasedWage.setText("6) Lönekostnader om varje anställda hade fått 10% löneökning ");

        btnFirstLetter.setText("7) Skriv ut första bokstaven för varje patient");

        btnNameDisease.setText("8) Skriv ut namn och sjukdom av varje patient. För kärlekssjuka ska ”svårt fall !”  skrivas  ut ");

        txtResult.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTotalWages)
                    .addComponent(btnIncreasedWage)
                    .addComponent(btnFirstLetter)
                    .addComponent(btnNameDisease)
                    .addComponent(btnInsomniaHosta)
                    .addComponent(btnNoCar)
                    .addComponent(btnNoOwner)
                    .addComponent(btnInsomnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtResult))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsomnia)
                        .addGap(7, 7, 7)
                        .addComponent(btnInsomniaHosta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNoCar)
                        .addGap(7, 7, 7)
                        .addComponent(btnNoOwner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTotalWages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncreasedWage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFirstLetter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNameDisease)))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsomniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsomniaActionPerformed
       
        String resultString = null;
        
        try {
            resultString = controller.getInsomnia();
        } catch (SQLException ex) {
            
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.txtResult.setText(resultString);
        
    }//GEN-LAST:event_btnInsomniaActionPerformed

    private void btnInsomniaHostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsomniaHostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsomniaHostaActionPerformed

    private void btnNoCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoCarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstLetter;
    private javax.swing.JButton btnIncreasedWage;
    private javax.swing.JButton btnInsomnia;
    private javax.swing.JButton btnInsomniaHosta;
    private javax.swing.JButton btnNameDisease;
    private javax.swing.JButton btnNoCar;
    private javax.swing.JButton btnNoOwner;
    private javax.swing.JButton btnTotalWages;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
