/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupp9_uppgift1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viktor Voigt
 * @author Jonas Ahrne
 * @author Joel Pennegård
 * @author August Ransnäs
 *
 */
public class MainView extends javax.swing.JFrame {

    private Controller controller;

    public MainView(Controller controller) {

        this.controller = controller;

        initComponents();

        this.populateCourseTable();

        this.populateStudentTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        tabMain = new javax.swing.JTabbedPane();
        panelFindStudent = new javax.swing.JPanel();
        lblFindStudent = new javax.swing.JLabel();
        txtFindStudentQuery = new javax.swing.JTextField();
        btnFindStudent = new javax.swing.JButton();
        separatorFindStudent = new javax.swing.JSeparator();
        scrollPaneFindStudent = new javax.swing.JScrollPane();
        tblFindStudent = new javax.swing.JTable();
        lblViewStudentPersonNbr = new javax.swing.JLabel();
        txtViewStudentPersonNbr = new javax.swing.JTextField();
        lblViewStudentFirstName = new javax.swing.JLabel();
        txtViewStudentFirstName = new javax.swing.JTextField();
        txtViewStudentLastName = new javax.swing.JTextField();
        lblViewStudentLastName = new javax.swing.JLabel();
        lblViewStudentPhoneNbr = new javax.swing.JLabel();
        txtViewStudentPhoneNbr = new javax.swing.JTextField();
        txtViewStudentEmail = new javax.swing.JTextField();
        lblViewStudentEmail = new javax.swing.JLabel();
        lblViewStudentAdress = new javax.swing.JLabel();
        txtViewStudentAdress = new javax.swing.JTextField();
        lblViewStudentPostCode = new javax.swing.JLabel();
        txtViewStudentPostCode = new javax.swing.JTextField();
        txtViewStudentCity = new javax.swing.JTextField();
        lblViewStudentCity = new javax.swing.JLabel();
        btnViewStudentDeleteStudent = new javax.swing.JButton();
        lblViewStudentPassedCourses = new javax.swing.JLabel();
        lblViewStudentNonPassedCourses = new javax.swing.JLabel();
        scrollPaneViewStudentPassedCourses = new javax.swing.JScrollPane();
        txtViewStudentPassedCourses = new javax.swing.JTextArea();
        scrollPaneViewStudentNonPassedCourses = new javax.swing.JScrollPane();
        txtViewStudentNonAreaPassedCourses = new javax.swing.JTextArea();
        lblViewStudentAddCourse = new javax.swing.JLabel();
        comboBoxViewStudentAddCourse = new javax.swing.JComboBox();
        btnViewStudentAddCourse = new javax.swing.JButton();
        btnRegisterStudentSave = new javax.swing.JButton();
        panelFindCourse = new javax.swing.JPanel();
        lblFindCourseInput = new javax.swing.JLabel();
        txtFindCourseInput = new javax.swing.JTextField();
        btnFindCourse = new javax.swing.JButton();
        separatorFindCourse = new javax.swing.JSeparator();
        scrollPaneFindCourse = new javax.swing.JScrollPane();
        tableFindCourse = new javax.swing.JTable();
        lblViewCourseCourseCode = new javax.swing.JLabel();
        txtViewCourseCode = new javax.swing.JTextField();
        lblViewCourseCourseName = new javax.swing.JLabel();
        txtViewCourseName = new javax.swing.JTextField();
        lblViewCourseCredits = new javax.swing.JLabel();
        txtViewCourseCredits = new javax.swing.JTextField();
        btnViewCourseDeleteCourse = new javax.swing.JButton();
        lblViewCoursePassedStudents = new javax.swing.JLabel();
        scrollPaneViewCoursePassedStudents = new javax.swing.JScrollPane();
        txtAreaViewCoursePassedStudents = new javax.swing.JTextArea();
        lblViewCourseNonPassedStudents = new javax.swing.JLabel();
        scrollPaneViewCourseNonPassedStudents = new javax.swing.JScrollPane();
        txtAreaViewCourseNonPassedStudents = new javax.swing.JTextArea();
        lblViewCourseStudentsWithA = new javax.swing.JLabel();
        txtViewCourseStudentsWithA = new javax.swing.JTextField();
        lblViewCourseHighestPassedCourses = new javax.swing.JLabel();
        scrollPaneViewCourseHighestPassedCourses = new javax.swing.JScrollPane();
        txtViewCourseHighestPassedCourses = new javax.swing.JTextArea();
        btnRegisterCourseSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studentsystem");

        lblFindStudent.setText("Sökterm:");

        btnFindStudent.setText("Sök");
        btnFindStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStudentActionPerformed(evt);
            }
        });

        tblFindStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneFindStudent.setViewportView(tblFindStudent);

        lblViewStudentPersonNbr.setText("Personnummer:");

        txtViewStudentPersonNbr.setEditable(false);

        lblViewStudentFirstName.setText("Förnamn:");

        txtViewStudentFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewStudentFirstNameActionPerformed(evt);
            }
        });

        lblViewStudentLastName.setText("Efternamn:");

        lblViewStudentPhoneNbr.setText("Telefonnummer:");

        lblViewStudentEmail.setText("E-post:");

        lblViewStudentAdress.setText("Adress:");

        lblViewStudentPostCode.setText("Postnummer:");

        lblViewStudentCity.setText("Ort:");

        btnViewStudentDeleteStudent.setText("Radera");
        btnViewStudentDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentDeleteStudentActionPerformed(evt);
            }
        });

        lblViewStudentPassedCourses.setText("Godkända kurser:");

        lblViewStudentNonPassedCourses.setText("Ej avslutade kurser:");

        txtViewStudentPassedCourses.setColumns(20);
        txtViewStudentPassedCourses.setRows(5);
        scrollPaneViewStudentPassedCourses.setViewportView(txtViewStudentPassedCourses);

        txtViewStudentNonAreaPassedCourses.setColumns(20);
        txtViewStudentNonAreaPassedCourses.setRows(5);
        scrollPaneViewStudentNonPassedCourses.setViewportView(txtViewStudentNonAreaPassedCourses);

        lblViewStudentAddCourse.setText("Lägg till kurs");

        comboBoxViewStudentAddCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnViewStudentAddCourse.setText("Lägg till");

        btnRegisterStudentSave.setText("Spara");
        btnRegisterStudentSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStudentSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFindStudentLayout = new javax.swing.GroupLayout(panelFindStudent);
        panelFindStudent.setLayout(panelFindStudentLayout);
        panelFindStudentLayout.setHorizontalGroup(
            panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindStudentLayout.createSequentialGroup()
                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFindStudentLayout.createSequentialGroup()
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViewStudentPersonNbr)
                                    .addComponent(lblViewStudentPhoneNbr)
                                    .addComponent(lblViewStudentEmail)
                                    .addComponent(lblViewStudentFirstName)
                                    .addComponent(lblViewStudentLastName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtViewStudentFirstName)
                                        .addComponent(txtViewStudentPhoneNbr)
                                        .addComponent(txtViewStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewStudentPersonNbr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtViewStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblViewStudentAdress)
                                            .addComponent(lblViewStudentCity)))
                                    .addComponent(lblViewStudentPostCode, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                                        .addComponent(btnRegisterStudentSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnViewStudentDeleteStudent))
                                    .addComponent(txtViewStudentAdress)
                                    .addComponent(txtViewStudentPostCode)
                                    .addComponent(txtViewStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scrollPaneFindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFindStudentLayout.createSequentialGroup()
                                .addComponent(lblFindStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFindStudentQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindStudent))))
                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewStudentAddCourse)
                            .addGroup(panelFindStudentLayout.createSequentialGroup()
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPaneViewStudentPassedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblViewStudentPassedCourses)
                                    .addComponent(lblViewStudentAddCourse))
                                .addGap(33, 33, 33)
                                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPaneViewStudentNonPassedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblViewStudentNonPassedCourses)))
                            .addComponent(comboBoxViewStudentAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorFindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelFindStudentLayout.setVerticalGroup(
            panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindStudentQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFindStudent)
                    .addComponent(btnFindStudent))
                .addGap(34, 34, 34)
                .addComponent(scrollPaneFindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(separatorFindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentPersonNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentPersonNbr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblViewStudentPhoneNbr)
                            .addComponent(txtViewStudentPhoneNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentEmail)))
                    .addGroup(panelFindStudentLayout.createSequentialGroup()
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentAdress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentPostCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewStudentCity))
                        .addGap(32, 32, 32)
                        .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewStudentDeleteStudent)
                            .addComponent(btnRegisterStudentSave))))
                .addGap(18, 18, 18)
                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewStudentPassedCourses)
                    .addComponent(lblViewStudentNonPassedCourses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneViewStudentNonPassedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneViewStudentPassedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblViewStudentAddCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxViewStudentAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewStudentAddCourse)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabMain.addTab("Student", panelFindStudent);

        lblFindCourseInput.setText("Kursnamn/Kurskod:");

        txtFindCourseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCourseInputActionPerformed(evt);
            }
        });

        btnFindCourse.setText("Sök");
        btnFindCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCourseActionPerformed(evt);
            }
        });

        tableFindCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableFindCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFindCourseMouseClicked(evt);
            }
        });
        scrollPaneFindCourse.setViewportView(tableFindCourse);

        lblViewCourseCourseCode.setText("Kurskod");

        txtViewCourseCode.setEditable(false);

        lblViewCourseCourseName.setText("Benämning");

        lblViewCourseCredits.setText("HP");

        btnViewCourseDeleteCourse.setText("Radera");
        btnViewCourseDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseDeleteCourseActionPerformed(evt);
            }
        });

        lblViewCoursePassedStudents.setText("Studenter med avslutad kurs");

        txtAreaViewCoursePassedStudents.setColumns(20);
        txtAreaViewCoursePassedStudents.setRows(5);
        scrollPaneViewCoursePassedStudents.setViewportView(txtAreaViewCoursePassedStudents);

        lblViewCourseNonPassedStudents.setText("Studenter med ej avslutad kurs");

        txtAreaViewCourseNonPassedStudents.setColumns(20);
        txtAreaViewCourseNonPassedStudents.setRows(5);
        scrollPaneViewCourseNonPassedStudents.setViewportView(txtAreaViewCourseNonPassedStudents);

        lblViewCourseStudentsWithA.setText("Andel studenter med betyg A (kan behöva döpa om variabel namnet här en aning):");

        lblViewCourseHighestPassedCourses.setText("Kurser med högst genomströmning");

        txtViewCourseHighestPassedCourses.setColumns(20);
        txtViewCourseHighestPassedCourses.setRows(5);
        scrollPaneViewCourseHighestPassedCourses.setViewportView(txtViewCourseHighestPassedCourses);

        btnRegisterCourseSave.setText("Spara");
        btnRegisterCourseSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCourseSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFindCourseLayout = new javax.swing.GroupLayout(panelFindCourse);
        panelFindCourse.setLayout(panelFindCourseLayout);
        panelFindCourseLayout.setHorizontalGroup(
            panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindCourseLayout.createSequentialGroup()
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFindCourseLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(separatorFindCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFindCourseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblViewCourseHighestPassedCourses)
                            .addComponent(scrollPaneFindCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                            .addGroup(panelFindCourseLayout.createSequentialGroup()
                                .addComponent(lblFindCourseInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFindCourseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindCourse))
                            .addGroup(panelFindCourseLayout.createSequentialGroup()
                                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViewCourseCourseCode)
                                    .addComponent(lblViewCourseCredits)
                                    .addComponent(lblViewCourseCourseName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtViewCourseName)
                                    .addComponent(txtViewCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtViewCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFindCourseLayout.createSequentialGroup()
                                        .addComponent(btnRegisterCourseSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnViewCourseDeleteCourse))))
                            .addComponent(scrollPaneViewCoursePassedStudents)
                            .addComponent(lblViewCoursePassedStudents)
                            .addComponent(lblViewCourseNonPassedStudents)
                            .addComponent(scrollPaneViewCourseNonPassedStudents)
                            .addGroup(panelFindCourseLayout.createSequentialGroup()
                                .addComponent(lblViewCourseStudentsWithA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtViewCourseStudentsWithA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPaneViewCourseHighestPassedCourses))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelFindCourseLayout.setVerticalGroup(
            panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindCourseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindCourseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFindCourseInput)
                    .addComponent(btnFindCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorFindCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneFindCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewCourseCourseCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewCourseCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewCourseCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewCourseCredits))
                .addGap(18, 18, 18)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCourseDeleteCourse)
                    .addComponent(btnRegisterCourseSave))
                .addGap(18, 18, 18)
                .addComponent(lblViewCoursePassedStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneViewCoursePassedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblViewCourseNonPassedStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneViewCourseNonPassedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFindCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewCourseStudentsWithA)
                    .addComponent(txtViewCourseStudentsWithA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewCourseHighestPassedCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneViewCourseHighestPassedCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );

        tabMain.addTab("Kurs", panelFindCourse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabMain.getAccessibleContext().setAccessibleName("Student");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewStudentFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewStudentFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewStudentFirstNameActionPerformed

    private void btnFindCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCourseActionPerformed

        String searchString = this.txtFindCourseInput.getText();

        DefaultTableModel dtm = controller.findCourses(searchString);

        this.tableFindCourse.setModel(dtm);



        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindCourseActionPerformed

    private void btnRegisterStudentSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStudentSaveActionPerformed

        String[] studentData = new String[8];

        studentData[0] = this.txtViewStudentFirstName.getText();
        studentData[1] = this.txtViewStudentFirstName.getText();
        studentData[2] = this.txtViewStudentLastName.getText();
        studentData[3] = this.txtViewStudentPhoneNbr.getText();
        studentData[4] = this.txtViewStudentEmail.getText();
        studentData[5] = this.txtViewStudentAdress.getText();
        studentData[6] = this.txtViewStudentPostCode.getText();
        studentData[7] = this.txtViewStudentCity.getText();

        if (controller.checkIfStudentExists(studentData[0]) == false) {



            this.controller.registerNewStudent(studentData);


        } else {

            JOptionPane.showMessageDialog(this,
                    "Student existerar redan. Personummer " + studentData[0] + " är inte unikt.",
                    "Kan inte registrera student",
                    JOptionPane.ERROR_MESSAGE);


        }

    }//GEN-LAST:event_btnRegisterStudentSaveActionPerformed

    private void btnRegisterCourseSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCourseSaveActionPerformed

        String[] courseData = new String[3];

        courseData[0] = this.txtViewCourseCode.getText();
        courseData[1] = this.txtViewCourseName.getText();
        courseData[2] = this.txtViewCourseCredits.getText();

        if (controller.checkIfCourseExists(courseData[0]) == false) {

            this.controller.registerNewCourse(courseData);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Kurs existerar redan. Kurskod " + courseData[0] + " finns redan i databasen.",
                    "Kan inte skapa kurs.",
                    JOptionPane.ERROR_MESSAGE);



        }


    }//GEN-LAST:event_btnRegisterCourseSaveActionPerformed

    private void btnViewCourseDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseDeleteCourseActionPerformed

        String courseCode = this.txtViewCourseCode.getText();

        if (controller.checkIfCourseExists(courseCode) == true) {

            this.controller.deleteCourse(courseCode);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Kan inte radera kurs. Kurskod " + courseCode + " finns inte i databasen.",
                    "Kan inte radera kurs.",
                    JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnViewCourseDeleteCourseActionPerformed

    private void btnViewStudentDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentDeleteStudentActionPerformed

        String personNbr = this.txtViewStudentPersonNbr.getText();

        if (controller.checkIfStudentExists(personNbr) == true) {

            this.controller.deleteStudent(personNbr);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Kan inte radera student. Personnummer " + personNbr + " finns inte i databasen.",
                    "Kan inte radera student.",
                    JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnViewStudentDeleteStudentActionPerformed

    private void txtFindCourseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCourseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCourseInputActionPerformed

    private void btnFindStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStudentActionPerformed

        String searchString = this.txtFindStudentQuery.getText();

        DefaultTableModel dtm = controller.findStudents(searchString);

        this.tblFindStudent.setModel(dtm);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindStudentActionPerformed

    private void tableFindCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFindCourseMouseClicked
        // TODO add your handling code here:
        int row = tableFindCourse.getSelectedRow();
        String ccode =(tableFindCourse.getModel().getValueAt(row, 0).toString());
        String cname =(tableFindCourse.getModel().getValueAt(row, 1).toString());
        String points =(tableFindCourse.getModel().getValueAt(row, 2).toString());
        txtViewCourseCode.setText(ccode);
        txtViewCourseName.setText(cname);
        txtViewCourseCredits.setText(points);
        
    }//GEN-LAST:event_tableFindCourseMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindCourse;
    private javax.swing.JButton btnFindStudent;
    private javax.swing.JButton btnRegisterCourseSave;
    private javax.swing.JButton btnRegisterStudentSave;
    private javax.swing.JButton btnViewCourseDeleteCourse;
    private javax.swing.JButton btnViewStudentAddCourse;
    private javax.swing.JButton btnViewStudentDeleteStudent;
    private javax.swing.JComboBox comboBoxViewStudentAddCourse;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblFindCourseInput;
    private javax.swing.JLabel lblFindStudent;
    private javax.swing.JLabel lblViewCourseCourseCode;
    private javax.swing.JLabel lblViewCourseCourseName;
    private javax.swing.JLabel lblViewCourseCredits;
    private javax.swing.JLabel lblViewCourseHighestPassedCourses;
    private javax.swing.JLabel lblViewCourseNonPassedStudents;
    private javax.swing.JLabel lblViewCoursePassedStudents;
    private javax.swing.JLabel lblViewCourseStudentsWithA;
    private javax.swing.JLabel lblViewStudentAddCourse;
    private javax.swing.JLabel lblViewStudentAdress;
    private javax.swing.JLabel lblViewStudentCity;
    private javax.swing.JLabel lblViewStudentEmail;
    private javax.swing.JLabel lblViewStudentFirstName;
    private javax.swing.JLabel lblViewStudentLastName;
    private javax.swing.JLabel lblViewStudentNonPassedCourses;
    private javax.swing.JLabel lblViewStudentPassedCourses;
    private javax.swing.JLabel lblViewStudentPersonNbr;
    private javax.swing.JLabel lblViewStudentPhoneNbr;
    private javax.swing.JLabel lblViewStudentPostCode;
    private javax.swing.JPanel panelFindCourse;
    private javax.swing.JPanel panelFindStudent;
    private javax.swing.JScrollPane scrollPaneFindCourse;
    private javax.swing.JScrollPane scrollPaneFindStudent;
    private javax.swing.JScrollPane scrollPaneViewCourseHighestPassedCourses;
    private javax.swing.JScrollPane scrollPaneViewCourseNonPassedStudents;
    private javax.swing.JScrollPane scrollPaneViewCoursePassedStudents;
    private javax.swing.JScrollPane scrollPaneViewStudentNonPassedCourses;
    private javax.swing.JScrollPane scrollPaneViewStudentPassedCourses;
    private javax.swing.JSeparator separatorFindCourse;
    private javax.swing.JSeparator separatorFindStudent;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tableFindCourse;
    private javax.swing.JTable tblFindStudent;
    private javax.swing.JTextArea txtAreaViewCourseNonPassedStudents;
    private javax.swing.JTextArea txtAreaViewCoursePassedStudents;
    private javax.swing.JTextField txtFindCourseInput;
    private javax.swing.JTextField txtFindStudentQuery;
    private javax.swing.JTextField txtViewCourseCode;
    private javax.swing.JTextField txtViewCourseCredits;
    private javax.swing.JTextArea txtViewCourseHighestPassedCourses;
    private javax.swing.JTextField txtViewCourseName;
    private javax.swing.JTextField txtViewCourseStudentsWithA;
    private javax.swing.JTextField txtViewStudentAdress;
    private javax.swing.JTextField txtViewStudentCity;
    private javax.swing.JTextField txtViewStudentEmail;
    private javax.swing.JTextField txtViewStudentFirstName;
    private javax.swing.JTextField txtViewStudentLastName;
    private javax.swing.JTextArea txtViewStudentNonAreaPassedCourses;
    private javax.swing.JTextArea txtViewStudentPassedCourses;
    private javax.swing.JTextField txtViewStudentPersonNbr;
    private javax.swing.JTextField txtViewStudentPhoneNbr;
    private javax.swing.JTextField txtViewStudentPostCode;
    // End of variables declaration//GEN-END:variables

    private void populateCourseTable() {

        DefaultTableModel dtm;

        dtm = controller.getAllCourses();

        System.out.println(dtm.getColumnCount());

        this.tableFindCourse.setModel(dtm);

    }

    private void populateStudentTable() {

        DefaultTableModel dtm;

        dtm = controller.getAllStudents();

        System.out.println(dtm.getColumnCount());

        this.tblFindStudent.setModel(dtm);
        
    
    }


}
